SQ5: Which four countries are leading in electric car and truck sales per Human Development Index (HDI), and how have these sales developed? (normalized to social / welfare)
Q5.B: How have these sales developed (for those 4 top leading countries)
SOCIAL/WELFARE

[general]
With the knowledge of the top 4 leading countries in electric car and truck sales normalized to Human Development Index (HDI), the development of these countries over the years can give interesting insights.
The following graphs show the development in sales from 2010 untill 2022.

